# Generated by Django 5.0.7 on 2024-08-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0011_alter_lotprocessus_temps_debut'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='cpn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='epn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='planificateur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
