# Generated by Django 5.0.7 on 2024-08-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0012_lot_cpn_lot_epn_lot_planificateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='projet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
