# Generated by Django 5.0.7 on 2024-08-23 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0013_lot_projet_lot_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='message',
            name='duree_reponse',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='temps_reponse',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='temps_reclamation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
