# Generated by Django 5.0.7 on 2024-08-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0014_alter_message_unique_together_message_duree_reponse_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('lot', 'processus', 'temps_reclamation')},
        ),
        migrations.AlterField(
            model_name='message',
            name='temps_reclamation',
            field=models.DateTimeField(),
        ),
        migrations.RemoveField(
            model_name='message',
            name='duree_reponse',
        ),
        migrations.RemoveField(
            model_name='message',
            name='temps_reponse',
        ),
    ]
