# Generated by Django 5.0.7 on 2024-08-23 08:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0015_alter_message_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_de_reponse',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='reponse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='temps_reclamation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
