# Generated by Django 5.0.7 on 2024-08-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0016_message_date_de_reponse_message_reponse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date_de_reponse',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reponse',
        ),
        migrations.AddField(
            model_name='lot',
            name='week',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='temps_reclamation',
            field=models.DateTimeField(),
        ),
    ]
